### ISSUE TITLE
Improve documentation: Add hint to https://verticalphotoplacer.github.io/VerticalPhotoPlacer/#prerequisites from description of the extension

### ISSUE THREAD

**Issue by Johann-Tree** [verticalphotoplacer/VerticalPhotoPlacerPlugin#5]
I just installed your extension in QGIS 3.10.4 on Ubuntu 20.0.4 LTS and tried to use it. QuickView worked not perfect, but ok.
Later I found https://verticalphotoplacer.github.io/VerticalPhotoPlacer/#prerequisites which says I have to install ExifTool first, add a special config file to the ExifTool folder and add this ExifTool folder to QGIS's PATH environment variable. 

I had ExifTool installed already and have seen no error messages so far. I wonder if it's still necessary to use the .ExifTool_config file? If so, you should mention https://verticalphotoplacer.github.io/VerticalPhotoPlacer/#prerequisites from the extension description.
 But where shall I put it on linux? Putting it with admin right into /usr/bin/ or /usr/share/libimage-exiftool-perl seems odd. How can I verify that the config file is found & is getting used?

**Comment by mdchuc** [comment]
Hi, the .ExifTool_config should be put on the same folder as the binary file. The folder location is up to you as long as it is known by QGIS (by setting in the QGIS PATH). 
Actually, for the altitude correction, VPP will write a custom tag (GroundAltitude) to the image metadata. Custom tag has to be specified in the .ExifTool_config so that Exiftool knows what to do. If there is no .ExifTool_config, the photos are still visualized with corrected altitude, but in the next time it is loaded, users have to correct again which is a bit inconvenience.
