### ISSUE TITLE
Does VPP still work

### ISSUE THREAD

**Issue by DWCons** [verticalphotoplacer/VerticalPhotoPlacerPlugin#9]
Does VPP still work? Am I doing something incorrectly? I am having the same trouble getting the VPP plugin to work in QGIS. I have followed the installation guide and did everything it said, but I still get this error:
![VPP](https://user-images.githubusercontent.com/126318149/221346549-ca267656-fa6d-420d-8ac9-f5c5ed0e05cf.png)

I have Installed exactly as the Installation Guide said:
![VPP folder](https://user-images.githubusercontent.com/126318149/221346584-0a354776-f65f-412d-b4d9-2241669333d4.png)
![File path](https://user-images.githubusercontent.com/126318149/221346593-d31d1b7a-a508-4b60-828f-ef786b41383d.png)

PLEASE HELP!
Deren

**Comment by pizagb** [comment]
> Does VPP still work? Am I doing something incorrectly? I am having the same trouble getting the VPP plugin to work in QGIS. I have followed the installation guide and did everything it said, but I still get this error: ![VPP](https://user-images.githubusercontent.com/126318149/221346549-ca267656-fa6d-420d-8ac9-f5c5ed0e05cf.png)
> 
> I have Installed exactly as the Installation Guide said: ![VPP folder](https://user-images.githubusercontent.com/126318149/221346584-0a354776-f65f-412d-b4d9-2241669333d4.png) ![File path](https://user-images.githubusercontent.com/126318149/221346593-d31d1b7a-a508-4b60-828f-ef786b41383d.png)
> 
> PLEASE HELP! Deren

It's working with QGIS 3.28.3 Firenze and LTR versions; well, at least it gets past this error.
The semicolon seems to be unnecessary in the PATH.
The version of exiftool I've downloaded is 20KB larger than yours, and comes with a "(-k)" in its name that has to be deleted for the plugin to load properly.
![image](https://github.com/verticalphotoplacer/VerticalPhotoPlacer/assets/40955756/72d1b9ef-de23-4538-b50c-d9bbcca946c6)

**Comment by DWCons** [comment]
Thanks for your reply.
Ive started again and it still doesn't work. I am so frustrated as I have followed each and every step to no avail.
Still get the same exception error as I posted originally.
I really need to use this plugin.
It seems I will have to wait until another plugin gets developed that will work for me

**Comment by Ojaybee** [comment]
This was solved as the OP had renamed exiftool to exiftool.exe without file extensions made visible in Windows. Therefore the full name was exiftool.exe.exe. Correcting this and the installation worked as expecting.

**Comment by DWCons** [comment]
Hi Oliver.

I am so, so grateful to you for assisting me - a HUGE thank you.

I have sent you a WeTransfer of some images of a recent audit it did in the
Northern Cape of South Africa.

I will certainly keep in touch and continue to watch your YouTube Channel.

Take care and thanks again.

Cheers for now.

Regards,
Deren

**Comment by Ipickedausername** [comment]
Hello, 

I see that you resolved your issue, what approach did you follow to resolve this error ? 

I tried to rename "exiftool(-k).exe" as exiftool(-k).exe.exe"
Changed the path of the folder that contain exiftool.exe. 
Added and removed the semicolon in the QGIS environment (in option system).
Tried on QGIS 3.26.0 and 3.32.0

I have the same error as presented above when trying to install from the official extensions repository:

![exiftool_err](https://github.com/verticalphotoplacer/VerticalPhotoPlacer/assets/72577399/416fca0a-2a02-4703-ad57-c12b6bc6fc02)

And I have a different error when I try to install it from a zip file:

![VPP_Notfound](https://github.com/verticalphotoplacer/VerticalPhotoPlacer/assets/72577399/eda30970-2a52-406c-bf0b-d9fe1aad0146)

Thank you

Regards, 


**Changelogs** : 

`Couldn't load plugin 'VerticalPhotoPlacer-master' due to an error when calling its classFactory() method 

KeyError: 'vertical_photo_placer' 
Traceback (most recent call last):
  File "C:\PROGRA~1/QGIS33~1.0/apps/qgis/./python\qgis\utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:\Users/Artemisia/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\VerticalPhotoPlacer-master\__init__.py", line 41, in classFactory
    from .vertical_photo_placer import VerticalPhotoPlacer
  File "C:\PROGRA~1/QGIS33~1.0/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/Artemisia/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\VerticalPhotoPlacer-master\vertical_photo_placer.py", line 44, in 
    from .vertical_photo_placer_dialog import VerticalPhotoPlacerDialog
  File "C:\PROGRA~1/QGIS33~1.0/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/Artemisia/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\VerticalPhotoPlacer-master\vertical_photo_placer_dialog.py", line 38, in 
    FORM_CLASS, _ = uic.loadUiType(os.path.join(
  File "C:\PROGRA~1/QGIS33~1.0/apps/qgis/./python\qgis\PyQt\uic\__init__.py", line 36, in __loadUiType
    return __PyQtLoadUiType(*args, **kwargs)
  File "C:\PROGRA~1\QGIS33~1.0\apps\Python39\lib\site-packages\PyQt5\uic\__init__.py", line 204, in loadUiType
    exec(code_string.getvalue(), ui_globals)
  File "", line 446, in 
  File "C:\PROGRA~1/QGIS33~1.0/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "", line 1007, in _find_and_load
  File "", line 982, in _find_and_load_unlocked
  File "", line 925, in _find_spec
  File "", line 1414, in find_spec
  File "", line 1380, in _get_spec
  File "", line 1246, in __iter__
  File "", line 1234, in _recalculate
  File "", line 1230, in _get_parent_path
KeyError: 'vertical_photo_placer'


Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS version: 3.32.0-Lima Lima, 311a8cb8a6 

Python Path:
C:\Users/Artemisia/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\OpenTopography-DEM-Downloader
C:/PROGRA~1/QGIS33~1.0/apps/qgis/./python
C:/Users/Artemisia/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/Artemisia/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS33~1.0/apps/qgis/./python/plugins
C:\PROGRA~1\QGIS33~1.0\apps\grass\grass82\etc\python
C:\Users\Artemisia\Documents
C:\Program Files\QGIS 3.32.0\bin\python39.zip
C:\PROGRA~1\QGIS33~1.0\apps\Python39\DLLs
C:\PROGRA~1\QGIS33~1.0\apps\Python39\lib
C:\Program Files\QGIS 3.32.0\bin
C:\PROGRA~1\QGIS33~1.0\apps\Python39
C:\PROGRA~1\QGIS33~1.0\apps\Python39\lib\site-packages
C:\PROGRA~1\QGIS33~1.0\apps\Python39\lib\site-packages\win32
C:\PROGRA~1\QGIS33~1.0\apps\Python39\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS33~1.0\apps\Python39\lib\site-packages\Pythonwin
C:/Users/Artemisia/AppData/Roaming/QGIS/QGIS3\profiles\default/python`

`Couldn't load plugin 'vertical_photo_placer' due to an error when calling its classFactory() method 

Exception: Cannot find exiftool, make sure to add exiftool to the system path variable. 
Traceback (most recent call last):
  File "C:\PROGRA~1/QGIS33~1.0/apps/qgis/./python\qgis\utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:\Users/Artemisia/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\vertical_photo_placer\__init__.py", line 41, in classFactory
    from .vertical_photo_placer import VerticalPhotoPlacer
  File "C:\PROGRA~1/QGIS33~1.0/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/Artemisia/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\vertical_photo_placer\vertical_photo_placer.py", line 46, in 
    from .model.process_metadata import ProcessMetadata
  File "C:\PROGRA~1/QGIS33~1.0/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/Artemisia/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\vertical_photo_placer\model\process_metadata.py", line 31, in 
    from .pyexiftool import ExifTool
  File "C:\PROGRA~1/QGIS33~1.0/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/Artemisia/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\vertical_photo_placer\model\pyexiftool.py", line 97, in 
    executable = resolveTool("exiftool")
  File "C:\Users/Artemisia/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\vertical_photo_placer\model\utility.py", line 103, in resolveTool
    raise Exception('Cannot find {0}, make sure to add {1} to the system path variable.'.format(prog, prog))
Exception: Cannot find exiftool, make sure to add exiftool to the system path variable.


Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS version: 3.32.0-Lima Lima, 311a8cb8a6 

Python Path:
C:\Users/Artemisia/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\OpenTopography-DEM-Downloader
C:/PROGRA~1/QGIS33~1.0/apps/qgis/./python
C:/Users/Artemisia/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/Artemisia/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS33~1.0/apps/qgis/./python/plugins
C:\PROGRA~1\QGIS33~1.0\apps\grass\grass82\etc\python
C:\Users\Artemisia\Documents
C:\Program Files\QGIS 3.32.0\bin\python39.zip
C:\PROGRA~1\QGIS33~1.0\apps\Python39\DLLs
C:\PROGRA~1\QGIS33~1.0\apps\Python39\lib
C:\Program Files\QGIS 3.32.0\bin
C:\PROGRA~1\QGIS33~1.0\apps\Python39
C:\PROGRA~1\QGIS33~1.0\apps\Python39\lib\site-packages
C:\PROGRA~1\QGIS33~1.0\apps\Python39\lib\site-packages\win32
C:\PROGRA~1\QGIS33~1.0\apps\Python39\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS33~1.0\apps\Python39\lib\site-packages\Pythonwin
C:/Users/Artemisia/AppData/Roaming/QGIS/QGIS3\profiles\default/python`

**Comment by Ipickedausername** [comment]
Finally, it worked for me, by removing (-k) from "exiftool(-k).exe"

**Comment by mdchuc** [comment]
I updated the document to notify users about this issue.
